FilePath = "./code.text"

[db]
host = "127.0.0.1" # mysql host ip
name = "code"      # the database this server used
port = "3306"
pwd = "123456"     # mysql password
user = "root"      # mysql username
