// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/invite/bind": {
            "post": {
                "description": "The exact message format to sign is here:\nhttps://github.com/stafiprotocol/invite-code-service/blob/main/pkg/utils/signature.go",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "v1"
                ],
                "summary": "bind user address and invite code",
                "parameters": [
                    {
                        "description": "bind",
                        "name": "param",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.ReqBind"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.Rsp"
                        }
                    }
                }
            }
        },
        "/v1/invite/genInviteCode": {
            "post": {
                "description": "The exact message format to sign is here:\nhttps://github.com/stafiprotocol/invite-code-service/blob/main/pkg/utils/signature.go",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "v1"
                ],
                "summary": "gen invite code",
                "parameters": [
                    {
                        "description": "gen",
                        "name": "param",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.ReqGen"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Rsp"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/api.RspGen"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/invite/tasks": {
            "get": {
                "description": "get tasks",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "v1"
                ],
                "summary": "get tasks",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Rsp"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/api.RspTasks"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/invite/userStatus": {
            "get": {
                "description": "get user status",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "v1"
                ],
                "summary": "get user status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "address",
                        "name": "address",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Rsp"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/api.RspUserStatus"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/invite/waterInviteCode": {
            "get": {
                "description": "get water invite code",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "v1"
                ],
                "summary": "get water invite code",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.Rsp"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/api.RspWaterInviteCode"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.ReqBind": {
            "type": "object",
            "properties": {
                "discord_id": {
                    "type": "string"
                },
                "invite_code": {
                    "type": "string"
                },
                "signature": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "integer"
                },
                "user_address": {
                    "type": "string"
                }
            }
        },
        "api.ReqGen": {
            "type": "object",
            "properties": {
                "signature": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "integer"
                },
                "user_address": {
                    "type": "string"
                }
            }
        },
        "api.RspGen": {
            "type": "object",
            "properties": {
                "invite_code": {
                    "type": "string"
                }
            }
        },
        "api.RspTasks": {
            "type": "object",
            "properties": {
                "tasks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/invite-code-service_api.Task"
                    }
                }
            }
        },
        "api.RspUserStatus": {
            "type": "object",
            "properties": {
                "invite_code": {
                    "type": "string"
                },
                "tasks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/invite-code-service_api.Task"
                    }
                }
            }
        },
        "api.RspWaterInviteCode": {
            "type": "object",
            "properties": {
                "invite_codes": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "invite-code-service_api.Task": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                }
            }
        },
        "utils.Rsp": {
            "type": "object",
            "properties": {
                "data": {},
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "point API",
	Description:      "point api document.\nError Codes:\n80001 Invalid parameters\n80002 Internal server error\n80003 User already bound\n80004 Invite code already bound\n80005 Signature verification failed\n80006 Task verification failed\n80007 Invite code does not exist\n80008 Invite code type mismatch\n80009 Invite codes not enough",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
