basePath: /api
definitions:
  api.RspUserInfo:
    properties:
      invite_code:
        type: string
    type: object
  utils.Rsp:
    properties:
      data: {}
      message:
        type: string
      status:
        type: string
    type: object
info:
  contact: {}
  description: point api document.
  title: point API
  version: "1.0"
paths:
  /v1/userInfo:
    get:
      consumes:
      - application/json
      description: get user info (rsp.status "80000":Success "80001":ParamErr "80002":InternalErr)
      parameters:
      - description: address
        in: query
        name: address
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/utils.Rsp'
            - properties:
                data:
                  $ref: '#/definitions/api.RspUserInfo'
              type: object
      summary: get user info
      tags:
      - v1
swagger: "2.0"
