basePath: /api
definitions:
  api.ReqBind:
    properties:
      invite_code:
        type: string
      signature:
        type: string
      user_address:
        type: string
    type: object
  api.RspBind:
    properties:
      invite_code:
        type: string
    type: object
  api.RspTasks:
    properties:
      tasks:
        items:
          $ref: '#/definitions/invite-code-service_api.Task'
        type: array
    type: object
  api.RspUserStatus:
    properties:
      bound:
        type: boolean
      invite_code:
        type: string
      tasks:
        items:
          $ref: '#/definitions/invite-code-service_api.Task'
        type: array
    type: object
  invite-code-service_api.Task:
    properties:
      description:
        type: string
      id:
        type: string
    type: object
  utils.Rsp:
    properties:
      data: {}
      message:
        type: string
      status:
        type: string
    type: object
info:
  contact: {}
  description: 'point api document. Error Codes: 80001 Invalid parameters; 80002 Internal
    server error; 80003 User already bound; 80004 Invite code already bound; 80005
    Signature verification failed; 80006 Task verification failed; 80007 Invite code
    does not exist; 80008 Invite code type mismatch; 80009 Invite codes not enough'
  title: point API
  version: "1.0"
paths:
  /v1/invite/bind:
    post:
      consumes:
      - application/json
      description: bind
      parameters:
      - description: bind
        in: body
        name: param
        required: true
        schema:
          $ref: '#/definitions/api.ReqBind'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/utils.Rsp'
            - properties:
                data:
                  $ref: '#/definitions/api.RspBind'
              type: object
      summary: bind user address and invite code
      tags:
      - v1
  /v1/invite/tasks:
    get:
      consumes:
      - application/json
      description: get tasks
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/utils.Rsp'
            - properties:
                data:
                  $ref: '#/definitions/api.RspTasks'
              type: object
      summary: get tasks
      tags:
      - v1
  /v1/invite/userStatus:
    get:
      consumes:
      - application/json
      description: get user status
      parameters:
      - description: address
        in: query
        name: address
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/utils.Rsp'
            - properties:
                data:
                  $ref: '#/definitions/api.RspUserStatus'
              type: object
      summary: get user status
      tags:
      - v1
swagger: "2.0"
