basePath: /api
definitions:
  api.Droplet:
    properties:
      available_count:
        type: integer
      invite_code:
        type: string
      round:
        type: integer
      total_count:
        type: integer
    type: object
  api.ReqBind:
    properties:
      discord_id:
        type: string
      discord_name:
        type: string
      invite_code:
        type: string
      signature:
        type: string
      timestamp:
        type: integer
      user_address:
        type: string
    type: object
  api.ReqGen:
    properties:
      signature:
        type: string
      timestamp:
        type: integer
      user_address:
        type: string
    type: object
  api.RspDroplets:
    properties:
      droplets:
        items:
          $ref: '#/definitions/api.Droplet'
        type: array
    type: object
  api.RspGen:
    properties:
      invite_code:
        type: string
    type: object
  api.RspSummary:
    properties:
      remaining_codes:
        type: integer
      remaining_task_codes:
        type: integer
      tasks:
        items:
          $ref: '#/definitions/api.Task'
        type: array
      total_codes:
        type: integer
      total_task_codes:
        type: integer
    type: object
  api.RspUserStatus:
    properties:
      invite_code:
        type: string
      tasks:
        items:
          $ref: '#/definitions/api.Task'
        type: array
    type: object
  api.Task:
    properties:
      description:
        type: string
      id:
        type: string
      type:
        type: string
      url:
        type: string
    type: object
  utils.Rsp:
    properties:
      data: {}
      message:
        type: string
      status:
        type: string
    type: object
info:
  contact: {}
  description: |-
    invite code api document.
    Error Codes:
    80001 Invalid parameters
    80002 Internal server error
    80003 User already bound
    80004 Invite code already bound
    80005 Signature verification failed
    80006 Task verification failed
    80007 Invite code does not exist
    80008 Invite code type mismatch
    80009 Invite codes not enough
    80010 Discord already bound
  title: invite code API
  version: "1.0"
paths:
  /v1/invite/bind:
    post:
      consumes:
      - application/json
      description: |-
        The exact message format to sign is here:
        https://github.com/stafiprotocol/invite-code-service/blob/main/pkg/utils/signature.go
      parameters:
      - description: bind
        in: body
        name: param
        required: true
        schema:
          $ref: '#/definitions/api.ReqBind'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.Rsp'
      summary: bind user address and invite code
      tags:
      - v1
  /v1/invite/droplets:
    get:
      consumes:
      - application/json
      description: get droplets
      parameters:
      - description: droplet
        in: query
        name: droplet
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/utils.Rsp'
            - properties:
                data:
                  $ref: '#/definitions/api.RspDroplets'
              type: object
      summary: get droplets
      tags:
      - v1
  /v1/invite/genInviteCode:
    post:
      consumes:
      - application/json
      description: |-
        The exact message format to sign is here:
        https://github.com/stafiprotocol/invite-code-service/blob/main/pkg/utils/signature.go
      parameters:
      - description: gen
        in: body
        name: param
        required: true
        schema:
          $ref: '#/definitions/api.ReqGen'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/utils.Rsp'
            - properties:
                data:
                  $ref: '#/definitions/api.RspGen'
              type: object
      summary: gen invite code
      tags:
      - v1
  /v1/invite/summary:
    get:
      consumes:
      - application/json
      description: get codes info and zealy task
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/utils.Rsp'
            - properties:
                data:
                  $ref: '#/definitions/api.RspSummary'
              type: object
      summary: get codes info and zealy task
      tags:
      - v1
  /v1/invite/userStatus:
    get:
      consumes:
      - application/json
      description: get user status
      parameters:
      - description: address
        in: query
        name: address
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/utils.Rsp'
            - properties:
                data:
                  $ref: '#/definitions/api.RspUserStatus'
              type: object
      summary: get user status
      tags:
      - v1
swagger: "2.0"
