basePath: /api
definitions:
  api.ReqBindDirect:
    properties:
      invite_code:
        type: string
      user_address:
        type: string
    type: object
  api.RspUserStatus:
    properties:
      bond_at:
        type: integer
      bound:
        type: boolean
      code_type:
        type: integer
      invite_code:
        type: string
    type: object
  utils.Rsp:
    properties:
      data: {}
      message:
        type: string
      status:
        type: string
    type: object
info:
  contact: {}
  description: 'point api document. Error Codes: 80001 Invalid parameters; 80002 Internal
    server error; 80003 User already bound; 80004 Invite code already bound; 80005
    Signature verification failed; 80006 Task verification failed; 80007 Invite code
    does not exist; 80008 Invite code type mismatch; 80009 Invite codes not enough'
  title: point API
  version: "1.0"
paths:
  /v1/invite/bindDirect:
    post:
      consumes:
      - application/json
      description: bind direct
      parameters:
      - description: bind direct req params
        in: body
        name: param
        required: true
        schema:
          $ref: '#/definitions/api.ReqBindDirect'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.Rsp'
      summary: bind direct
      tags:
      - v1
  /v1/invite/bindTask:
    post:
      consumes:
      - application/json
      description: bind direct
      parameters:
      - description: bind direct req params
        in: body
        name: param
        required: true
        schema:
          $ref: '#/definitions/api.ReqBindDirect'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.Rsp'
      summary: bind direct
      tags:
      - v1
  /v1/invite/userStatus:
    get:
      consumes:
      - application/json
      description: get user status
      parameters:
      - description: address
        in: query
        name: address
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/utils.Rsp'
            - properties:
                data:
                  $ref: '#/definitions/api.RspUserStatus'
              type: object
      summary: get user status
      tags:
      - v1
swagger: "2.0"
